### ISSUE TITLE
Crash 

### ISSUE THREAD

**Issue by Sunekaer** [blay09/CookingForBlockheads#493] opened 2021-01-14 10:24 UTC
Crash when changing pages between recipe categories in JEI: https://paste.sunekaer.com/nikaciqice.rb
Crash when placing Trash Can from Rats https://paste.sunekaer.com/gabivilera.rb

Both crashes looks the same to me

Forge .36
Minecraft: 1.16.4
Mods list: https://paste.sunekaer.com/udefayunop.css

**Comment by BlayTheNinth** [comment] 2021-01-17 14:10
This is most likely caused by another mod in the pack or some other weird Forge (?) issue. The class in question hasn't changed in 10 months, and there's no real reason for it to fail loading if not for external forces.

**Comment by BlayTheNinth** [comment] 2021-03-13 13:46
Closing since this seems to have fixed itself

**Closed as completed by BlayTheNinth** 2021-03-13 13:46 UTC
Labels: Bug, Crash
