### ISSUE TITLE
[suggestion] Recursive recipe

### ISSUE THREAD

**Issue by Piratdu52** [blay09/CookingForBlockheads#180] opened 2016-12-11 19:16 UTC
Currently CookingForBlockheads shown only recipy **directly** craftable, so if i have some wheat it will only show me flour and not bread and toast.
Why not adding recipe result to the list of ingredients an rerun the "avaibleRecipe" function ? If the result of the last batch == the result of the current batch show the list of recipe.

**Comment by BlayTheNinth** [comment] 2017-01-02 18:08
duplicate of #112

**Closed as completed by BlayTheNinth** 2017-01-02 18:08 UTC
Labels: Feature, Duplicate
