### ISSUE TITLE
Outside counter block (enhancment)

### ISSUE THREAD

**Issue by OutcastZeroOne** [blay09/CookingForBlockheads#432] opened 2020-03-21 22:54 UTC
there is a counter block for inside corners of counter space, but what if your base leads to a design with and outside corner? Maybe something like a counter with a beveled edge.
![2020-03-21_15 49 42](https://user-images.githubusercontent.com/8162248/77238286-15968180-6b8c-11ea-8f4c-bfe1877b0058.png)

https://i.pinimg.com/originals/60/92/ae/6092aede0c5ffd1af9022b90c8ce4cd0.jpg

**Comment by BlayTheNinth** [comment] 2020-03-22 08:18
Duplicate of #244

**Closed as completed by BlayTheNinth** 2020-03-22 08:18 UTC
Labels: Feature, Duplicate
