### ISSUE TITLE
Consuming utensils when crafting. (Croptopia)

### ISSUE THREAD

**Issue by StriderTR** [blay09/CookingForBlockheads#695] opened 2024-03-20 06:52 UTC
### Minecraft Version

1.20.4

### Mod Loader

Forge

### Mod Loader Version

49.0.31

### Mod Version

18.0.4

### Balm Version

9.0.6

### Describe the Issue

When crafting Croptopia (3.0.4) foods with Blockheads, the utensils are being consumed. I've also noticed other oddities like not being able to craft salt, it just cooks the water in the oven and spits out the same water. 

When crafting these food the "old fashioned way" in a crafting table, it works normally. The utensils are NOT consumed and all other crafting works as expected. This is why I assume it's a Blockheads issue, but I may be wrong. It wouldn't
 be the first time. :)

![modlist](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/97561185/ba3dd022-56b7-41cb-b710-16addd86c4fd)
![MC-Blockheads-Croptopia](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/97561185/228feb30-2e73-4a3c-bfd6-8c13509270f5)

### Logs

No logs to link. Images attached.

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Optifine. Still happens whithout Optifine.

**Comment by BlayTheNinth** [comment] 2024-03-20 07:49
Duplicate of #691

**Closed as not planned by BlayTheNinth** 2024-03-20 07:49 UTC
Labels: Bug, Duplicate
