### ISSUE TITLE
Kitchen isnt registering ingredients

### ISSUE THREAD

**Issue by violetkitty87** [blay09/CookingForBlockheads#664] opened 2023-10-01 14:18 UTC
### Minecraft Version

1.20.x

### Mod Loader

Forge

### Mod Loader Version

47.1.3

### Mod Version

16.0.1

### Balm Version

7.1.4

### Describe the Issue

The mod was recently just updated in the pack I'm playing. I have the kitchen set up the same way I had before, and it doesn't work after this update. It is not registering any ingredients whether in cabinets or fridges or even my inventory. It was working the other day when the server was on an older version of the mod. I am not the only one having this issue on this server. I am not the one hosting the server, so I cannot give you logs from the server, but I can on my end.

Log is too long for pastebin had to use google docs.

### Logs

https://docs.google.com/document/d/1yTvGkB1MMURo2iZN83vXBJtQcS3JEMvchRdKRGqfhII/edit?usp=sharing

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

oculus

**Comment by BlayTheNinth** [comment] 2023-12-06 18:29
Duplicate of #590

**Closed as not planned by BlayTheNinth** 2023-12-06 18:29 UTC
Labels: Bug, Duplicate, Forge
