### ISSUE TITLE
(suggestion) Pam's harvestcraft machines could be part of the multiblock

### ISSUE THREAD

**Issue by NerdySpider** [blay09/CookingForBlockheads#353] opened 2019-01-17 07:27 UTC
I had an idea where blocks such as the presser for sugar, etc. or the grinder for doubling meat and making better burgers. It could be useful to use instead of using the manual sugar crafting. or if its not avaiable, maybe a recreation of the block with the cooking for blockheads style, that requires the block from pam's in the first place for the crafting recipe?

e.g 
![2019-01-17_18 24 07](https://user-images.githubusercontent.com/29170640/51302078-735da400-1a85-11e9-8ea3-9d9cb0de9481.png)

Could be the crafting recipe for the new presser. the diamond could be a nugget variation since a full diamond could be too expensive.

**Comment by BlayTheNinth** [comment] 2019-10-05 19:17
Duplicate of #285

**Closed as completed by BlayTheNinth** 2019-10-05 19:17 UTC
Labels: Feature, Duplicate
