### ISSUE TITLE
Compatibility: Recipe has been rotated

### ISSUE THREAD

**Issue by winderine** [blay09/CookingForBlockheads#671] opened 2023-11-22 12:37 UTC
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Fabric

### Mod Loader Version

0.14.22

### Mod Version

16.0.1

### Balm Version

none?

### Describe the Issue

Recipe in cooking table is rotated from recipe in JEI for the Meadow cheese sandwich, causing crafting from the cooking table to fail.

![CookingTableUsesWrongRecipe](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/52304340/6fc3cec0-159d-4970-a763-77b808f1ffaa)
![ThisIsNotTheRecipe](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/52304340/4174c36b-a8cf-4bf5-97d1-57a6fe049a63)
![JEI](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/52304340/9b80c340-d1dd-4b47-85fd-a3a87a33c68e)
![TheActualRecipeWorks](https://github.com/TwelveIterationMods/CookingForBlockheads/assets/52304340/768dbded-d197-4385-aa62-8a84bad8b4c0)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Cottagecraft modpack has 297 mods including sodium, indium and carpet

**Comment by BlayTheNinth** [comment] 2023-12-06 18:31
Duplicate of #665

**Closed as not planned by BlayTheNinth** 2023-12-06 18:31 UTC
Labels: Bug, Duplicate, Fabric
