### ISSUE TITLE
Feature Placement Issue 

### ISSUE THREAD

**Issue by ImExlow** [blay09/CookingForBlockheads#607] opened 2022-07-26 15:16 UTC
### Minecraft Version

1.16.x

### Mod Loader

Forge

### Mod Loader Version

1.16.5-36.2.39

### Mod Version

1.16.5-9.3.4

### Describe the Issue

This issue crashes my 3rd party forge server after my girlfriend moved into a chuck last night. Anytime she joins the server goes down. I will be reporting this issue to Ice And Fire as well. 

### Logs

https://pastebin.com/gJxAm26h

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Optifine is running client side, not on server side.

**Comment by BlayTheNinth** [comment] 2022-07-27 07:14
Duplicate of #604, fixed in Ice and Fire

**Closed as not planned by BlayTheNinth** 2022-07-27 07:14 UTC
Labels: Bug, Duplicate, Crash
