### ISSUE TITLE
Not enough Ingredients when it's all connected

### ISSUE THREAD

**Issue by ShikoiKurogami** [blay09/CookingForBlockheads#692] opened 2024-03-14 05:38 UTC
### Minecraft Version

1.20.1 (LTS)

### Mod Loader

Forge

### Mod Loader Version

47.2.0

### Mod Version

16.0.3

### Balm Version

7.2.2

### Describe the Issue

I play on a server, but recently, the cooking table shows "Not enough ingredients", despite the kitchen being connected. It is all in 1 chunk, and even if I take the pam's kitchen tools off the racks into inventory, it still says the same thing. I have a picture linked to show my inventory, plus the darkened background to show it's all connected.

[https://imgur.com/a/dAJnUNF](url)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Embeddium

**Comment by BlayTheNinth** [comment] 2024-03-14 06:07
Duplicate of #590. The cause is unfortunately not yet known.

**Closed as not planned by BlayTheNinth** 2024-03-14 06:07 UTC
Labels: Bug, Duplicate
