### ISSUE TITLE
1.16.2 crash

### ISSUE THREAD

**Issue by Warbringer12** [blay09/CookingForBlockheads#469] opened 2020-08-30 02:34 UTC
[crash-2020-08-29_19.33.42-client.txt](https://github.com/blay09/CookingForBlockheads/files/5146265/crash-2020-08-29_19.33.42-client.txt)
forge: 33.0.20
version: 1.16.2-9.1.0

**Comment by BlayTheNinth** [comment] 2020-08-30 07:49
Duplicate of #465

**Closed as completed by BlayTheNinth** 2020-08-30 07:49 UTC
Labels: Bug, Duplicate, Crash
