### ISSUE TITLE
Game freezing on startup

### ISSUE THREAD

**Issue by VoidMini** [blay09/CookingForBlockheads#631] opened 2023-01-28 11:25 UTC
### Minecraft Version

1.19 - 1.19.2

### Mod Loader

Forge

### Mod Loader Version

43.2.1 ~ 43.2.4

### Mod Version

13.3.0

### Describe the Issue

I made a modspack for me and my friends and I have an issue. I don't know if it's something to do with the processor but on my 2 friends, who use Ryzen 7 and Nvidia RTX 3060 the game boot normally. But on mine Intel core i7 12700H, RTX 3060 the game freezes. Sometimes I have to try and open it like 10 times for it to finally start. I tried using 9gb of RAM and the problem always occur. It doesn't even show the MOJANG screen.
This behavior doesn't happen when disabling the mod.

My mod list: https://gist.github.com/VoidMini/fe936996ed3e740a154fcaea7891c1d2

### Logs

https://gist.github.com/VoidMini/4e7d9d12720f8366f3f9931d328b5354

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Rubidium, Spark. The issue still happens after disabling these

**Comment by DJFPaul** [comment] 2023-01-28 20:56
I can confirm this issue exists FOR SOME USERS. (Including the randomness of it sometimes launches, other times white screen)
We've started a modpack in 1.19.2 and 3 out of our 11 Players ran into this issue.
After lots oft trial and error we sourced the issues comming from either Cooking for Blockoheads or a specific incompatibility.

It freezes right before it would log this: Module Step CONSTRUCT_CLIENT
That's the next message that would come, if it hadn't frozen.

Here is our modlist: https://gist.github.com/DJFPaul/8488cef85bd2fc49584c418746487d7b

**Comment by Twisted-Code** [comment] 2023-04-24 02:46
Rather off-topic, but it is hilarious to me that github thinks this was added "issues" before it existed. Something about time zones or maybe DST must be confusing it.
<img width="373" alt="image" src="https://user-images.githubusercontent.com/7110033/233888938-ca58cf05-b4ca-4df3-9a66-a6b7c156bf85.png">
<img width="364" alt="image" src="https://user-images.githubusercontent.com/7110033/233889084-5cb04390-8b63-43ad-b113-88bf28d399b6.png">

**Comment by BlayTheNinth** [comment] 2024-06-11 10:24
Closing since 1.19 is no longer supported and there hasn't been any recent reports of this happening.

**Closed as not planned by BlayTheNinth** 2024-06-11 10:24 UTC
Labels: Bug, Needs Repro, EOL, Forge
