### ISSUE TITLE
Multi-stage crafting

### ISSUE THREAD

**Issue by blipadouzi** [blay09/CookingForBlockheads#284] opened 2018-05-21 08:16 UTC
Would it be possible to add multi-stage crafting?  For example, if I had potatoes, wheat, cheese, stock & all the necessary cookware... the kitchen would detect that I could make a Poutine.

(BTW, thank you for adding Poutine to the mod, best food ever  ;)  )

Regards

**Comment by BlayTheNinth** [comment] 2018-05-21 08:36
Duplicate of #112

Cooking for Blockheads also doesn't add any food items, it's probably Pam's Harvestcraft adding Poutine. Never had Poutine but I doubt I would like it, it looks stringy and gross :P

**Closed as completed by BlayTheNinth** 2018-05-21 08:36 UTC
Labels: Feature, Duplicate

**Comment by blipadouzi** [comment] 2018-05-21 08:45
Thanks for the reference, I did search but my parameters came up empty. And yes my bad on the poutine. I sometimes forget they are 2 separate mods. I never use one without the other. Keep up the great work.
