### ISSUE TITLE
Sort by Saturation sorts alphabetically

### ISSUE THREAD

**Issue by Syndaryl** [blay09/CookingForBlockheads#309] opened 2018-08-26 11:40 UTC
Sort by Saturation *does* sort the zero-saturation items to the bottom, but all the non-zero saturation items are sorted alphabetically, rather than by saturation.

**Comment by BlayTheNinth** [comment] 2018-09-02 08:40
Did this happen with any particular items or mods? Was some mod like Hunger Overhaul or AppleCore installed, that may have had an impact on food saturation? Testing with Vanilla the sorting seems to be correct.

**Comment by Syndaryl** [comment] 2018-09-02 12:50
I have both; it's not sorted by the current saturation or the old saturation, it's straight up alphabetical. I'm guessing that's a fail-over mode?

**Comment by Syndaryl** [comment] 2018-09-02 14:53
Notably sort by hunger restored is working fine, even though Pams and Hunger Overhaul both mess with hunger too.

**Comment by BlayTheNinth** [comment] 2018-09-02 15:43
Alphabetical is indeed the fallback in case the saturation of two items is the same.

However, I just tried with AppleCore, AppleSkin, Hunger Overhaul and Pam's installed and everything still seems to be sorting fine on both hunger restored and saturation.

![image](https://user-images.githubusercontent.com/1933180/44957863-9c670900-aed7-11e8-8141-02df5bbac14b.png)

**Comment by BlayTheNinth** [comment] 2020-05-27 18:38
Closing since this couldn't be reproduced

**Closed as completed by BlayTheNinth** 2020-05-27 18:38 UTC
Labels: Bug
