### ISSUE TITLE
Cooking Table User Experience Improvements

### ISSUE THREAD

**Issue by TheCutter** [blay09/CookingForBlockheads#436] opened 2020-04-02 09:04 UTC
Using the Cooking Table with a NoFilter Book and clicking through the recipes it would be cool to have a button or keyboard shortcut to go back to the last recipe like JEI's Back Button.
Also it would be really nice to have the possibility to craft a missing ingredient which is shown in the recipe matrix. 
This way it would be much easier to craft missing items for a higher tier food item.

**Comment by Skydragonsz** [comment] 2020-04-02 09:10
Somewhat related to #112

**Comment by TheCutter** [comment] 2020-04-02 09:22
Somewhat you are right, but my idea is not about automatic cascaded crafting.
How the cooking table works today is really annoying if you want to craft some high tier food from harvestcraft. You need to click through the missing ingredients, find some, search it on the right side, craft it, search the high tier food again, click through the missing ingredients, so on and so on...

**Comment by BlayTheNinth** [comment] 2020-04-04 07:21
Duplicate of #343

**Closed as completed by BlayTheNinth** 2020-04-04 07:21 UTC
Labels: Feature, Duplicate
