### ISSUE TITLE
Dyeable Oven [Feature Request]

### ISSUE THREAD

**Issue by ghost** [blay09/CookingForBlockheads#475] opened 2020-10-01 16:34 UTC
Hello, 

Firstly, thanks for the mod, it's brilliant and I love it.

Would it be possible to have the Oven be Dyeable just like all the fridge and the countertops/sink are, please?

Thank you for the constant mod development!

**Comment by BlayTheNinth** [comment] 2020-10-03 06:52
Duplicate of #401

**Closed as completed by BlayTheNinth** 2020-10-03 06:52 UTC
Labels: Feature, Duplicate
