### ISSUE TITLE
Dragon Survival makes all Recipes Dissapear

### ISSUE THREAD

**Issue by Era4721** [blay09/CookingForBlockheads#630] opened 2023-01-23 01:35 UTC
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

Forge 40.2.0

### Mod Version

1.18.2-12.2.0

### Describe the Issue

With the mod added, the cooking bench and stove stopped working (all recipes refused to show up, even with viable items in the inventory, weather the fridge was connected to the blocks or not)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

Rubidium + Oculus

**Comment by Era4721** [comment] 2023-01-23 01:35
https://www.curseforge.com/minecraft/mc-mods/dragons-survival

**Comment by BlackAures1** [comment] 2023-01-24 10:49
I've tested it and I don't see a problem.
![image](https://user-images.githubusercontent.com/43911230/214272430-8ab4a701-b8fd-4e1b-8811-3fb75fea6363.png)
![image](https://user-images.githubusercontent.com/43911230/214272013-f570e4a6-4a96-4b30-8e1a-bb379600cfc8.png)

**Comment by BlayTheNinth** [comment] 2023-02-26 14:07
Most likely duplicate of #590

**Closed as not planned by BlayTheNinth** 2023-02-26 14:07 UTC
Labels: Bug, Mod Compatibility, Duplicate
